#!/usr/bin/env bash
# ---------------------------------------------------------------------------
#
# Description: LSF job file. 
#
# Revision history:
# 2017-03-15  Created (version 8.1), based on the LSF tmplate
# ---------------------------------------------------------------------------


# LSF Settings
###############################################################################

#BSUB -J runtimeletter-mainjob_id_placeholder
#BSUB -W 150:00
#BSUB -R "rusage[mem=1000]"
##BSUB -R "select[scratch2]"
##BSUB -R "span[ptile=4]"
#BSUB -R "rusage[ngpus=0.5]"
#BSUB -n 2
#BSUB -q gpu
#BSUB -oo batchsystem/output-files/job-mainjob_id_placeholder.main-%J.out
#BSUB -wt '5'
#BSUB -wa 'USR1' 

# Job Information
##################################################################################
echo
echo "                    *** Job Information ***                    "
echo "==============================================================="
echo 
echo "Environment variables"
echo "------------------------"
env
echo
echo
echo "Job infos by bjobs"
echo "------------------------"
bjobs $LSB_JOBID

# Running the Job - Screening of the Ligands
######################################################################
echo
echo "                    *** Job Output ***                    "
echo "==========================================================="
echo

# Functions
# Standard error response 
error_response_std() {
    echo "Error was trapped" 1>&2
    echo "Error in bash script $0" 1>&2
    echo "Error on line $1" 1>&2
    echo "Environment variables" 1>&2 
    echo "----------------------------------" 1>&2
    env 1>&2
}
trap 'error_response_std $LINENO' ERR

# Handling signals
time_near_limit() {
    echo "The script ${BASH_SOURCE[0]} caught a time limit signal. Trying to start a new job."
}
trap 'time_near_limit' 10

termination_signal() {
    echo "The script ${BASH_SOURCE[0]} caught a termination signal. Stopping job."
    exit 1
}
trap 'termination_signal' 1 2 3 9 12 15

# Printing final job information
print_job_infos_end() {
    # Job information
    echo
    echo "                     *** Final Job Information ***                    "
    echo "======================================================================"
    echo
    echo "Starting time:" $STARTINGTIME
    echo "Ending time:  " $(date)
    echo
}

# Work to be done by the job

# Variables
HQF_STARTDATE="$(date +%Y%m%d%m%S-%N)"
export HQF_STARTDATE
source /opt/gpu.sh
export CUDA_VISIBLE_DEVICES

# Preparing folders
mkdir -p batchsystem/output-files

# Running the subjobs
#main_code_placeholder

# Waiting for the subjobs to finish
wait


# Printing final information
print_job_infos_end
